### ISSUE TITLE
Enable geometry editing in the Layer Editing

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1432]
As a user I expect to be able to edit feature geometries to make them more complete and accurate. For example, perhaps I am tracking the changing shape of a political border over time. Whenever an annexation occurs, I want to update the polygon shape to reflect that political change.

**Issue**
Currently, geometry editing is disabled in the Layer Editor. Geometry editing needs to be renabled in the workflow.

**Subtasks to include**
- [x] Undo #1244 so that the "Edit Geometry" field appears again in the editor sidebar
- [ ] Addressing bugs in the geometry-edit tool
- [ ] Updating the tooltips to guide the user appropriately

**Comment by josellausas** [comment]
PR : https://github.com/MapStory/MapLoom/pull/49

**Comment by jonpmarino** [comment]
there are 2 other tasks in this issue not done. Should we break them out into new issues or take this one out of review?

**Comment by jonpmarino** [comment]
Using lab.mapstory on July 10, using Chrome - Current editing behavior on lab.mapstory.org: user cannot get the draw tool either on point or polygon layers to actually change the feature shape or location. Also, when using the "add to feature" function we got this error message:

![screen shot 2018-07-10 at 11 52 43 am](https://user-images.githubusercontent.com/2573761/42525269-52350fe0-8438-11e8-9500-20bdef314a1c.jpg)
