### ISSUE TITLE
UC Configuration & Code Clean-up

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1659]

**Comment by lhcramer** [comment]
- [x] Fix thumbnails in UC (do we need configurable thumbnail basemap for that?)
- [x] Login via GeoAxis always goes to Edit Profile page
- [x] Remove social media fields from profile page
- [x] Username is only pulling in GeoAxis first name, need more info
- [x] Implement auto-logout?
- [x] Run.sh fix to pull in external dependencies
- [x] Docker images aren’t getting pulled from Quay.io during deployment build, pulled during start-up (bug in Bosh build script?)
- [x] Fix point-style and polygon style in GeoServer (1657)
- [x] Initiative pages use wrong URL (1626)
