### ISSUE TITLE
Composer UX Enhancements & Fixes (Pri 1)

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1667]
This epic is major blockers to creating a story in composer including: 

- [x] Move frames and pins into chapters within the config object on front-end
- [x] You can add layers that don't exist by typing a layer name that doesn't exist and hitting add.
- [x] Pins from chapter 2 are showing up in chapter 1 on a published story.
- [x] Reloading afterwards sometimes shows different results than was previously shown. (Verify/create ticket)
- [x] Pins disappear when you move to another chapter, the info box is there but the actual circle is gone.
- [x] Deleting a frame doesn’t remove the box on the map
- [x] Bulk upload of pins doesn’t populate coordinates correctly
- [x] Changing chapter, going to frames and then back, makes the circles disappear.; When go back from the previous chapter, the Pin bubbles disappear until you “Update the Map”
- [x] Change frame button from “Save” to “Add”; save message for frame as in line label
- [x] Fix CSS for text box for pins so it doesn’t grow forever
- [x] In styling, classification bar is covering up button at the bottom

**Comment by lhcramer** [comment]
@darinacosta, @copaskevin, are we good to close this Epic?
