### ISSUE TITLE
Post-Template Refactor Clean-up

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1833]
Epic to capture all regressions/bugs from the recent GeoNode Template work upon testing. 

- [x] Verify layers/Stories can be added to Teams (organizations and Initiatives) 
- [x] Clarify delta between GeoNode "Groups" and MapStoryScapes "Teams" 
- [x] Replace comments with threaded comments
- [ ] Metadata form is different
- [x] Append button is missing
