### ISSUE TITLE
Commit Back to Upstream

### ISSUE THREAD

**Issue by lhcramer** [MapStory/mapstory#1939]
Componetize and submit GNIPs for all applicable MapStory Functionality back to core GeoNode. Those GNIPs that are not accepted should be packaged into community modules. 

- [ ] Storytelling GNIP (including pins, frames, chapters) 
- [ ] Organizations and Initiatives GNIP
- [ ] Journal GNIP 
- [ ] Create to OSGeo-Importer
- [ ] Append to OSGeo-Importer
