### ISSUE TITLE
Generate site-wide announcements when services are down or failing that will affect user experience

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#374]
As we are in development phase, our services go down regularly (GeoServer, Geogig, importer, etc). We should have a method for communicating to the user when something is down that will affect their user experience, insofar as we can know about a service being down.

Work was done for a health check (https://mapstory.org/ht/). But, we don't tie this to anything for the user. GeoNode has an "announcements" tool. Perhaps a site-wide announcement could be generated and published until the service is rebooted or fixed? Otherwise its difficult for users to know if they are seeing a bug, or if some back-end service being down is causing their issues.

If a full connection to a site-wide announcement doesn't make sense, perhaps we could at least have a page (such as status.mapstory.org) that makes it easy to see if a service is down. Example = status.slack.com

**Comment by josellausas** [comment]
Got health_check working again:

<img width="666" alt="screen shot 2017-03-06 at 1 30 12 pm" src="https://cloud.githubusercontent.com/assets/4162671/23626561/f22dc08a-0272-11e7-9ecd-a49aafc657c9.png">

**Comment by josellausas** [comment]
This could be broken down into smaller issues/tasks:

- [x] #526 : Fix Health check
- [ ] #546 : Detect and create an alert when services become unavailable
- [ ] #547 : Generate site-wide announcements when an alert is created
