### ISSUE TITLE
Homepage review - TODO list & minor issues

### ISSUE THREAD

**Issue by sarasafavi** [MapStory/mapstory#769]
-This may be split into additional stories as needed, for now I'm just collecting things I notice as I see them into one master list: note I am only reviewing this from a user perspective, not checking e.g., CSS/HTML against the spec_

- [x] Nav header is missing `MapStory` logo; dark instead of white
![image](https://user-images.githubusercontent.com/1209376/27152861-e23f625a-5114-11e7-86d3-6eae8cb8fdb2.png)
_header in Invision ^_
![image](https://user-images.githubusercontent.com/1209376/27152878-f55c76e8-5114-11e7-8e2b-6ce3a4b61ab8.png)
_header on my local dev instance ^_

- [x] `Featured Mapstories` tiles should be fixed, not variable, sizes:
![image](https://user-images.githubusercontent.com/1209376/27154989-9e4d3678-511c-11e7-9692-ae74f5af537a.png)

- [x] In `Featured MapStories...` section, the first story ("Fracking Sites in West Virginia") points at a local URL (that doesn't exist, unless running on prod). Other featured stories have fully-qualified mapstory.org URLs. Additionally, "Fracking Sites..." goes directly to the /view endpoint, others do not

- [x] *"LEARN MORE"* buttons all go to `/search` page right now; Invision design specifies: 
```Learn More buttons all go to Get Started page. Eventually each "Learn More" will go to its own page about that specific task```

- [x] Punctuation is a bit variable throughout (ex: some paragraphs have closing periods, some do not: see e.g., the `How It Works` sections). This should be made consistent, one way or another (Invision spec has closing periods on all).

- [x] Typo: `the more likey we are to treat it` (/s/likey/likely) - in blue topo section

- [ ] Text for `"Help Us Keep Improving"` section, above `DONATE` button, appears to be missing (Invision shows two more sentences here).

- [x] "DONATE" buttons do nothing

- [x] "Subscribe to our newsletter" form does nothing _(do we have a newsletter or is this a placeholder that should be removed?)_

- [x] In footer, link to `the Wiki` does nothing

- [x] Social buttons missing from footer

- [x] version number missing from footer

- [x] "Sign up" header text doesn't disappear when users are logged in
![image](https://user-images.githubusercontent.com/1209376/27348596-9f0b0022-55c2-11e7-9d29-495fe8ef98d5.png)

**Comment by emilyashley** [comment]
Thanks Sara! I'll take a look at some of these. 

@zunware , re: header and footer  feedback. The header and footer settings vary by THEME (blue, orange, default) in localsettings.py and some of the images and text are also modified in the django admin [panel](http://192.168.56.151/admin/mapstory/customsite/) after deployment -- so some of these might appear broken on a local deploy.
