### ISSUE TITLE
Integrate story pins into new composer

### ISSUE THREAD

**Issue by trepagnier** [MapStory/mapstory#805]

**Comment by Coop56** [comment]
This is a fairly large task that should likely be broken down into more specific tasks.  I'm starting out by getting to know the codebase that @darinacosta has been working on and then I'll start to figure out what tasks need done here and create additional tickets and perhaps a milestone.

**Comment by josellausas** [comment]
Glynnis was working on this, still needs to be finished:

Finalize design for StoryPins tab: #272

**Comment by josellausas** [comment]
Rename everything to 'StoryPins' according to :  #1118

**Comment by josellausas** [comment]
Dividing this issue into:

- [x] Pin Sidebar #1194 
- [x] Create Pin form #1195
- [x] Time pickers #1197
- [ ] Show in timeline #1198
- [ ] Show in map #1199
- [x] Pin map placement #1200
- [ ] Save Pin list #1201
- [x] Bulk Pin upload #1202
- [ ] Pin Drag move. #1258

**Comment by josellausas** [comment]
Still need to finalize work in issue #272.
